### ISSUE TITLE
Goroutine leak in `CheckHealth()`

### ISSUE THREAD

**Issue by kelleyk** [hightouchio/passage#25]
I think that there's a goroutine leak in [`func (m *healthcheckManager) CheckHealth()`](https://github.com/hightouchio/passage/blob/f9963c0418f036118fb2a6ffa8c248d0e024c21f/cmd/passage/healthcheck.go#L27).  If multiple heathchecks return an error, each goroutine will try to send into `cerr`, but only one of those sends will ever succeed (because the parent goroutine will receive that value and return it).  All of the other goroutines will block forever on trying to send.

(Also, on [this line](https://github.com/hightouchio/passage/blob/f9963c0418f036118fb2a6ffa8c248d0e024c21f/cmd/passage/healthcheck.go#L40), I think that the idiomatic thing to do is to return `ctx.Err()`.)

**Comment by andrewpage** [comment]
Thanks for the report @kelleyk! I've addressed the issue and it will be merged & released soon.
